//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST10097490_POE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Id { get; set; }
        public string CourseName { get; set; }
        public string CourseCode { get; set; }
        public string UserName { get; set; }
        public int Credit { get; set; }
        public int ClassHoursPerWeek { get; set; }
        public int NumberOfWeeks { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
